### ISSUE TITLE
Error when running learn.fit_one_cycle(500, 1.0E-3) a second time

### ISSUE THREAD

**Issue by OCsteve** [timeseriesAI/tsai#204]
Error when running learn.fit_one_cycle(500, 1.0E-3) a second time. This happens when running on CPUs or GPUs. TypeError: 'numpy.float64' object is not callable

In [5]: learn.fit_one_cycle(500, 1.0E-3)
█epoch     train_loss  valid_loss  None      time    
██Traceback (most recent call last):

  File "C:\Users\Steve\AppData\Local\Temp/ipykernel_295712/4252417616.py", line 1, in <module>
    learn.fit_one_cycle(500, 1.0E-3)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\callback\schedule.py", line 113, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 212, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 207, in _do_epoch
    self._do_epoch_validate()

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 203, in _do_epoch_validate
    with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 169, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\tsai\learner.py", line 37, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 165, in _with_events
    self(f'after_{event_type}');  final()

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastcore\foundation.py", line 154, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastcore\basics.py", line 666, in map_ex
    return list(res)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastcore\basics.py", line 651, in __call__
    return self.func(*fargs, **kwargs)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\callback\core.py", line 45, in __call__
    if self.run and _run: res = getattr(self, event_name, noop)()

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 504, in after_batch
    for met in mets: met.accumulate(self.learn)

  File "C:\Users\Steve\anaconda3\envs\torchenv\lib\site-packages\fastai\learner.py", line 426, in accumulate
    self.total += learn.to_detach(self.func(learn.pred, *learn.yb))*bs

TypeError: 'numpy.float64' object is not callable

computer_setup()
os             : Windows-10-10.0.19041-SP0
python         : 3.7.0
tsai           : 0.2.23
fastai         : 2.5.2
fastcore       : 1.3.26
torch          : 1.9.0+cu102
n_cpus         : 8
device         : cpu

**Comment by oguiza** [comment]
Hi @OCsteve, 

I'm sorry but I can't reproduce the issue with the information you have provided. 

I've tried this: 

```
X, y, splits = get_UCR_data('LSST', split_data=False)
tfms = [None, TSClassification()]
batch_tfms = TSStandardize(by_sample=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms)
learn = ts_learner(dls, InceptionTimePlus, metrics=accuracy, cbs=[ShowGraph()])
learn.fit_one_cycle(10, 1e-2)
learn.fit_one_cycle(10, 1e-2)
```

and it works well. 

Could you provide a code snippet to reproduce your error?

**Comment by OCsteve** [comment]
Hi Ignacio,

I can't seem to reproduce the issue now myself. Let's leave the issue open for a week and if the problem arises again I will notify you. The only changes are:
X, y, splits = combine_split_data([Xtrain, Xtest], [Ytrain, Ytest])
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
