### ISSUE TITLE
Error(s) in loading state_dict for InceptionTimePlus during optuna optimization

### ISSUE THREAD

**Issue by geoHeil** [timeseriesAI/tsai#230]
During an optimization run of a TSAI model after several steps in Optuna I get a very strange error:

```
Trial 8 failed because of the following error: RuntimeError('Error(s) in loading state_dict for InceptionTimePlus:\n\tMissing key(s) in state_dict: "backbone.0.inception.0.bottleneck.0.weight", "backbone.0.inception.0.convs.0.0.weight", "backbone.0.inception.0.convs.1.0.weight", "backbone.0.inception.0.convs.2.0.weight", "backbone.0.inception.0.mp_conv.1.0.weight", "backbone.0.inception.0.norm.weight", "backbone.0.inception.0.norm.bias", "backbone.0.inception.0.norm.running_mean", "backbone.0.inception.0.norm.running_var", "backbone.0.inception.1.bottleneck.0.weight", "backbone.0.inception.1.convs.0.0.weight", "backbone.0.inception.1.convs.1.0.weight", "backbone.0.inception.1.convs.2.0.weight", "backbone.0.inception.1.mp_conv.1.0.weight", "backbone.0.inception.1.norm.weight", "backbone.0.inception.1.norm.bias", "backbone.0.inception.1.norm.running_mean", "backbone.0.inception.1.norm.running_var", "backbone.0.inception.2.bottleneck.0.weight", "backbone.0.inception.2.convs.0.0.weight", "backbone.0.inception.2.convs.1.0.weight", "backbone.0.inception.2.convs.2.0.weight", "backbone.0.inception.2.mp_conv.1.0.weight", "backbone.0.inception.2.norm.weight", "backbone.0.inception.2.norm.bias", "backbone.0.inception.2.norm.running_mean", "backbone.0.inception.2.norm.running_var", "backbone.0.inception.3.bottleneck.0.weight", "backbone.0.inception.3.convs.0.0.weight", "backbone.0.inception.3.convs.1.0.weight", "backbone.0.inception.3.convs.2.0.weight", "backbone.0.inception.3.mp_conv.1.0.weight", "backbone.0.inception.3.norm.weight", "backbone.0.inception.3.norm.bias", "backbone.0.inception.3.norm.running_mean", "backbone.0.inception.3.norm.running_var", "backbone.0.inception.4.bottleneck.0.weight", "backbone.0.inception.4.convs.0.0.weight", "backbone.0.inception.4.convs.1.0.weight", "backbone.0.inception.4.convs.2.0.weight", "backbone.0.inception.4.mp_conv.1.0.weight", "backbone.0.inception.4.norm.weight", "backbone.0.inception.4.norm.bias", "backbone.0.inception.4.norm.running_mean", "backbone.0.inception.4.norm.running_var", "backbone.0.inception.5.bottleneck.0.weight", "backbone.0.inception.5.convs.0.0.weight", "backbone.0.inception.5.convs.1.0.weight", "backbone.0.inception.5.convs.2.0.weight", "backbone.0.inception.5.mp_conv.1.0.weight", "backbone.0.inception.5.norm.weight", "backbone.0.inception.5.norm.bias", "backbone.0.inception.5.norm.running_mean", "backbone.0.inception.5.norm.running_var", "backbone.0.shortcut.0.0.weight", "backbone.0.shortcut.0.1.weight", "backbone.0.shortcut.0.1.bias", "backbone.0.shortcut.0.1.running_mean", "backbone.0.shortcut.0.1.running_var", "backbone.0.shortcut.1.weight", "backbone.0.shortcut.1.bias", "backbone.0.shortcut.1.running_mean", "backbone.0.shortcut.1.running_var", "head.0.1.1.weight", "head.0.1.1.bias". \n\tUnexpected key(s) in state_dict: "W_pos", "W_P.weight", "W_P.bias", "encoder.layers.0.self_attn.W_Q.weight", "encoder.layers.0.self_attn.W_K.weight", "encoder.layers.0.self_attn.W_V.weight", "encoder.layers.0.self_attn.W_O.weight", "encoder.layers.0.batchnorm_attn.weight", "encoder.layers.0.batchnorm_attn.bias", "encoder.layers.0.batchnorm_attn.running_mean", "encoder.layers.0.batchnorm_attn.running_var", "encoder.layers.0.batchnorm_attn.num_batches_tracked", "encoder.layers.0.ff.0.weight", "encoder.layers.0.ff.0.bias", "encoder.layers.0.ff.2.weight", "encoder.layers.0.ff.2.bias", "encoder.layers.0.batchnorm_ffn.weight", "encoder.layers.0.batchnorm_ffn.bias", "encoder.layers.0.batchnorm_ffn.running_mean", "encoder.layers.0.batchnorm_ffn.running_var", "encoder.layers.0.batchnorm_ffn.num_batches_tracked", "encoder.layers.1.self_attn.W_Q.weight", "encoder.layers.1.self_attn.W_K.weight", "encoder.layers.1.self_attn.W_V.weight", "encoder.layers.1.self_attn.W_O.weight", "encoder.layers.1.batchnorm_attn.weight", "encoder.layers.1.batchnorm_attn.bias", "encoder.layers.1.batchnorm_attn.running_mean", "encoder.layers.1.batchnorm_attn.running_var", "encoder.layers.1.batchnorm_attn.num_batches_tracked", "encoder.layers.1.ff.0.weight", "encoder.layers.1.ff.0.bias", "encoder.layers.1.ff.2.weight", "encoder.layers.1.ff.2.bias", "encoder.layers.1.batchnorm_ffn.weight", "encoder.layers.1.batchnorm_ffn.bias", "encoder.layers.1.batchnorm_ffn.running_mean", "encoder.layers.1.batchnorm_ffn.running_var", "encoder.layers.1.batchnorm_ffn.num_batches_tracked", "encoder.layers.2.self_attn.W_Q.weight", "encoder.layers.2.self_attn.W_K.weight", "encoder.layers.2.self_attn.W_V.weight", "encoder.layers.2.self_attn.W_O.weight", "encoder.layers.2.batchnorm_attn.weight", "encoder.layers.2.batchnorm_attn.bias", "encoder.layers.2.batchnorm_attn.running_mean", "encoder.layers.2.batchnorm_attn.running_var", "encoder.layers.2.batchnorm_attn.num_batches_tracked", "encoder.layers.2.ff.0.weight", "encoder.layers.2.ff.0.bias", "encoder.layers.2.ff.2.weight", "encoder.layers.2.ff.2.bias", "encoder.layers.2.batchnorm_ffn.weight", "encoder.layers.2.batchnorm_ffn.bias", "encoder.layers.2.batchnorm_ffn.running_mean", "encoder.layers.2.batchnorm_ffn.running_var", "encoder.layers.2.batchnorm_ffn.num_batches_tracked", "head.1.weight", "head.1.bias". ')
Traceback (most recent call last):
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/optuna/_optimize.py", line 216, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_178357/4137781455.py", line 26, in objective_tsai_archs
    lrr = learn.lr_find()
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/callback/schedule.py", line 283, in lr_find
    with self.no_logging(): self.fit(n_epoch, cbs=cb)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py", line 165, in _with_events
    self(f'after_{event_type}');  final()
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastcore/foundation.py", line 154, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastcore/basics.py", line 666, in map_ex
    return list(res)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastcore/basics.py", line 651, in __call__
    return self.func(*fargs, **kwargs)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/callback/core.py", line 45, in __call__
    if self.run and _run: res = getattr(self, event_name, noop)()
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/callback/schedule.py", line 193, in after_fit
    self.learn.load('_tmp', with_opt=True)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py", line 359, in load
    load_model(file, self.model, self.opt, device=device, **kwargs)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py", line 51, in load_model
    get_model(model).load_state_dict(model_state, strict=strict)
  File "/home/at/heilerg/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for InceptionTimePlus:
	Missing key(s) in state_dict: "backbone.0.inception.0.bottleneck.0.weight", "backbone.0.inception.0.convs.0.0.weight", "backbone.0.inception.0.convs.1.0.weight", "backbone.0.inception.0.convs.2.0.weight", "backbone.0.inception.0.mp_conv.1.0.weight", "backbone.0.inception.0.norm.weight", "backbone.0.inception.0.norm.bias", "backbone.0.inception.0.norm.running_mean", "backbone.0.inception.0.norm.running_var", "backbone.0.inception.1.bottleneck.0.weight", "backbone.0.inception.1.convs.0.0.weight", "backbone.0.inception.1.convs.1.0.weight", "backbone.0.inception.1.convs.2.0.weight", "backbone.0.inception.1.mp_conv.1.0.weight", "backbone.0.inception.1.norm.weight", "backbone.0.inception.1.norm.bias", "backbone.0.inception.1.norm.running_mean", "backbone.0.inception.1.norm.running_var", "backbone.0.inception.2.bottleneck.0.weight", "backbone.0.inception.2.convs.0.0.weight", "backbone.0.inception.2.convs.1.0.weight", "backbone.0.inception.2.convs.2.0.weight", "backbone.0.inception.2.mp_conv.1.0.weight", "backbone.0.inception.2.norm.weight", "backbone.0.inception.2.norm.bias", "backbone.0.inception.2.norm.running_mean", "backbone.0.inception.2.norm.running_var", "backbone.0.inception.3.bottleneck.0.weight", "backbone.0.inception.3.convs.0.0.weight", "backbone.0.inception.3.convs.1.0.weight", "backbone.0.inception.3.convs.2.0.weight", "backbone.0.inception.3.mp_conv.1.0.weight", "backbone.0.inception.3.norm.weight", "backbone.0.inception.3.norm.bias", "backbone.0.inception.3.norm.running_mean", "backbone.0.inception.3.norm.running_var", "backbone.0.inception.4.bottleneck.0.weight", "backbone.0.inception.4.convs.0.0.weight", "backbone.0.inception.4.convs.1.0.weight", "backbone.0.inception.4.convs.2.0.weight", "backbone.0.inception.4.mp_conv.1.0.weight", "backbone.0.inception.4.norm.weight", "backbone.0.inception.4.norm.bias", "backbone.0.inception.4.norm.running_mean", "backbone.0.inception.4.norm.running_var", "backbone.0.inception.5.bottleneck.0.weight", "backbone.0.inception.5.convs.0.0.weight", "backbone.0.inception.5.convs.1.0.weight", "backbone.0.inception.5.convs.2.0.weight", "backbone.0.inception.5.mp_conv.1.0.weight", "backbone.0.inception.5.norm.weight", "backbone.0.inception.5.norm.bias", "backbone.0.inception.5.norm.running_mean", "backbone.0.inception.5.norm.running_var", "backbone.0.shortcut.0.0.weight", "backbone.0.shortcut.0.1.weight", "backbone.0.shortcut.0.1.bias", "backbone.0.shortcut.0.1.running_mean", "backbone.0.shortcut.0.1.running_var", "backbone.0.shortcut.1.weight", "backbone.0.shortcut.1.bias", "backbone.0.shortcut.1.running_mean", "backbone.0.shortcut.1.running_var", "head.0.1.1.weight", "head.0.1.1.bias". 
	Unexpected key(s) in state_dict: "W_pos", "W_P.weight", "W_P.bias", "encoder.layers.0.self_attn.W_Q.weight", "encoder.layers.0.self_attn.W_K.weight", "encoder.layers.0.self_attn.W_V.weight", "encoder.layers.0.self_attn.W_O.weight", "encoder.layers.0.batchnorm_attn.weight", "encoder.layers.0.batchnorm_attn.bias", "encoder.layers.0.batchnorm_attn.running_mean", "encoder.layers.0.batchnorm_attn.running_var", "encoder.layers.0.batchnorm_attn.num_batches_tracked", "encoder.layers.0.ff.0.weight", "encoder.layers.0.ff.0.bias", "encoder.layers.0.ff.2.weight", "encoder.layers.0.ff.2.bias", "encoder.layers.0.batchnorm_ffn.weight", "encoder.layers.0.batchnorm_ffn.bias", "encoder.layers.0.batchnorm_ffn.running_mean", "encoder.layers.0.batchnorm_ffn.running_var", "encoder.layers.0.batchnorm_ffn.num_batches_tracked", "encoder.layers.1.self_attn.W_Q.weight", "encoder.layers.1.self_attn.W_K.weight", "encoder.layers.1.self_attn.W_V.weight", "encoder.layers.1.self_attn.W_O.weight", "encoder.layers.1.batchnorm_attn.weight", "encoder.layers.1.batchnorm_attn.bias", "encoder.layers.1.batchnorm_attn.running_mean", "encoder.layers.1.batchnorm_attn.running_var", "encoder.layers.1.batchnorm_attn.num_batches_tracked", "encoder.layers.1.ff.0.weight", "encoder.layers.1.ff.0.bias", "encoder.layers.1.ff.2.weight", "encoder.layers.1.ff.2.bias", "encoder.layers.1.batchnorm_ffn.weight", "encoder.layers.1.batchnorm_ffn.bias", "encoder.layers.1.batchnorm_ffn.running_mean", "encoder.layers.1.batchnorm_ffn.running_var", "encoder.layers.1.batchnorm_ffn.num_batches_tracked", "encoder.layers.2.self_attn.W_Q.weight", "encoder.layers.2.self_attn.W_K.weight", "encoder.layers.2.self_attn.W_V.weight", "encoder.layers.2.self_attn.W_O.weight", "encoder.layers.2.batchnorm_attn.weight", "encoder.layers.2.batchnorm_attn.bias", "encoder.layers.2.batchnorm_attn.running_mean", "encoder.layers.2.batchnorm_attn.running_var", "encoder.layers.2.batchnorm_attn.num_batches_tracked", "encoder.layers.2.ff.0.weight", "encoder.layers.2.ff.0.bias", "encoder.layers.2.ff.2.weight", "encoder.layers.2.ff.2.bias", "encoder.layers.2.batchnorm_ffn.weight", "encoder.layers.2.batchnorm_ffn.bias", "encoder.layers.2.batchnorm_ffn.running_mean", "encoder.layers.2.batchnorm_ffn.running_var", "encoder.layers.2.batchnorm_ffn.num_batches_tracked", "head.1.weight", "head.1.bias". 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_178357/4243327112.py in <module>
      1 study = optuna.create_study(direction='maximize', pruner=optuna.pruners.HyperbandPruner())
----> 2 study.optimize(objective_tsai_archs, n_trials=num_optuna_trials) # , n_jobs=20 #show_progress_bar=False

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    399             )
    400 
--> 401         _optimize(
    402             study=self,
    403             func=func,

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     63     try:
     64         if n_jobs == 1:
---> 65             _optimize_sequential(
     66                 study,
     67                 func,

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    160 
    161         try:
--> 162             trial = _run_trial(study, func, catch)
    163         except Exception:
    164             raise

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    265 
    266     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 267         raise func_err
    268     return trial
    269 

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    214 
    215     try:
--> 216         value_or_values = func(trial)
    217     except exceptions.TrialPruned as e:
    218         # TODO(mamu): Handle multi-objective cases.

/tmp/ipykernel_178357/4137781455.py in objective_tsai_archs(trial)
     24         #learn = Learner(dls, model, metrics=accuracy, cbs=FastAIPruningCallback(trial))
     25         model, learn = make_learner(arch, dls, k, None, cbs_extra=FastAIPruningCallback(trial))
---> 26         lrr = learn.lr_find()
     27         suggested_lr = lrr.valley
     28 

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggest_funcs)
    281     n_epoch = num_it//len(self.dls.train) + 1
    282     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 283     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    284     if suggest_funcs is not None:
    285         lrs, losses = tensor(self.recorder.lrs[num_it//10:-5]), tensor(self.recorder.losses[num_it//10:-5])

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    219             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    220             self.n_epoch = n_epoch
--> 221             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    222 
    223     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    163         try: self(f'before_{event_type}');  f()
    164         except ex: self(f'after_cancel_{event_type}')
--> 165         self(f'after_{event_type}');  final()
    166 
    167     def all_batches(self):

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py in __call__(self, event_name)
    139 
    140     def ordered_cbs(self, event): return [cb for cb in self.cbs.sorted('order') if hasattr(cb, event)]
--> 141     def __call__(self, event_name): L(event_name).map(self._call_one)
    142 
    143     def _call_one(self, event_name):

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastcore/foundation.py in map(self, f, gen, *args, **kwargs)
    152     def range(cls, a, b=None, step=None): return cls(range_of(a, b=b, step=step))
    153 
--> 154     def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
    155     def argwhere(self, f, negate=False, **kwargs): return self._new(argwhere(self, f, negate, **kwargs))
    156     def filter(self, f=noop, negate=False, gen=False, **kwargs):

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastcore/basics.py in map_ex(iterable, f, gen, *args, **kwargs)
    664     res = map(g, iterable)
    665     if gen: return res
--> 666     return list(res)
    667 
    668 # Cell

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastcore/basics.py in __call__(self, *args, **kwargs)
    649             if isinstance(v,_Arg): kwargs[k] = args.pop(v.i)
    650         fargs = [args[x.i] if isinstance(x, _Arg) else x for x in self.pargs] + args[self.maxi+1:]
--> 651         return self.func(*fargs, **kwargs)
    652 
    653 # Cell

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py in _call_one(self, event_name)
    143     def _call_one(self, event_name):
    144         if not hasattr(event, event_name): raise Exception(f'missing {event_name}')
--> 145         for cb in self.cbs.sorted('order'): cb(event_name)
    146 
    147     def _bn_bias_state(self, with_bias): return norm_bias_params(self.model, with_bias).map(self.opt.state)

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/callback/core.py in __call__(self, event_name)
     43                (self.run_valid and not getattr(self, 'training', False)))
     44         res = None
---> 45         if self.run and _run: res = getattr(self, event_name, noop)()
     46         if event_name=='after_fit': self.run=True #Reset self.run to True at each end of fit
     47         return res

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/callback/schedule.py in after_fit(self)
    191         tmp_f = self.path/self.model_dir/'_tmp.pth'
    192         if tmp_f.exists():
--> 193             self.learn.load('_tmp', with_opt=True)
    194             os.remove(tmp_f)
    195 

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py in load(self, file, device, **kwargs)
    357     if self.opt is None: self.create_opt()
    358     file = join_path_file(file, self.path/self.model_dir, ext='.pth')
--> 359     load_model(file, self.model, self.opt, device=device, **kwargs)
    360     return self
    361 

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/fastai/learner.py in load_model(file, model, opt, with_opt, device, strict)
     49     hasopt = set(state)=={'model', 'opt'}
     50     model_state = state['model'] if hasopt else state
---> 51     get_model(model).load_state_dict(model_state, strict=strict)
     52     if hasopt and with_opt:
     53         try: opt.load_state_dict(state['opt'])

~/development/conda_envs/anomalydetection-nnet/lib/python3.8/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1221 
   1222         if len(error_msgs) > 0:
-> 1223             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1224                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1225         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for InceptionTimePlus:
	Missing key(s) in state_dict: "backbone.0.inception.0.bottleneck.0.weight", "backbone.0.inception.0.convs.0.0.weight", "backbone.0.inception.0.convs.1.0.weight", "backbone.0.inception.0.convs.2.0.weight", "backbone.0.inception.0.mp_conv.1.0.weight", "backbone.0.inception.0.norm.weight", "backbone.0.inception.0.norm.bias", "backbone.0.inception.0.norm.running_mean", "backbone.0.inception.0.norm.running_var", "backbone.0.inception.1.bottleneck.0.weight", "backbone.0.inception.1.convs.0.0.weight", "backbone.0.inception.1.convs.1.0.weight", "backbone.0.inception.1.convs.2.0.weight", "backbone.0.inception.1.mp_conv.1.0.weight", "backbone.0.inception.1.norm.weight", "backbone.0.inception.1.norm.bias", "backbone.0.inception.1.norm.running_mean", "backbone.0.inception.1.norm.running_var", "backbone.0.inception.2.bottleneck.0.weight", "backbone.0.inception.2.convs.0.0.weight", "backbone.0.inception.2.convs.1.0.weight", "backbone.0.inception.2.convs.2.0.weight", "backbone.0.inception.2.mp_conv.1.0.weight", "backbone.0.inception.2.norm.weight", "backbone.0.inception.2.norm.bias", "backbone.0.inception.2.norm.running_mean", "backbone.0.inception.2.norm.running_var", "backbone.0.inception.3.bottleneck.0.weight", "backbone.0.inception.3.convs.0.0.weight", "backbone.0.inception.3.convs.1.0.weight", "backbone.0.inception.3.convs.2.0.weight", "backbone.0.inception.3.mp_conv.1.0.weight", "backbone.0.inception.3.norm.weight", "backbone.0.inception.3.norm.bias", "backbone.0.inception.3.norm.running_mean", "backbone.0.inception.3.norm.running_var", "backbone.0.inception.4.bottleneck.0.weight", "backbone.0.inception.4.convs.0.0.weight", "backbone.0.inception.4.convs.1.0.weight", "backbone.0.inception.4.convs.2.0.weight", "backbone.0.inception.4.mp_conv.1.0.weight", "backbone.0.inception.4.norm.weight", "backbone.0.inception.4.norm.bias", "backbone.0.inception.4.norm.running_mean", "backbone.0.inception.4.norm.running_var", "backbone.0.inception.5.bottleneck.0.weight", "backbone.0.inception.5.convs.0.0.weight", "backbone.0.inception.5.convs.1.0.weight", "backbone.0.inception.5.convs.2.0.weight", "backbone.0.inception.5.mp_conv.1.0.weight", "backbone.0.inception.5.norm.weight", "backbone.0.inception.5.norm.bias", "backbone.0.inception.5.norm.running_mean", "backbone.0.inception.5.norm.running_var", "backbone.0.shortcut.0.0.weight", "backbone.0.shortcut.0.1.weight", "backbone.0.shortcut.0.1.bias", "backbone.0.shortcut.0.1.running_mean", "backbone.0.shortcut.0.1.running_var", "backbone.0.shortcut.1.weight", "backbone.0.shortcut.1.bias", "backbone.0.shortcut.1.running_mean", "backbone.0.shortcut.1.running_var", "head.0.1.1.weight", "head.0.1.1.bias". 
	Unexpected key(s) in state_dict: "W_pos", "W_P.weight", "W_P.bias", "encoder.layers.0.self_attn.W_Q.weight", "encoder.layers.0.self_attn.W_K.weight", "encoder.layers.0.self_attn.W_V.weight", "encoder.layers.0.self_attn.W_O.weight", "encoder.layers.0.batchnorm_attn.weight", "encoder.layers.0.batchnorm_attn.bias", "encoder.layers.0.batchnorm_attn.running_mean", "encoder.layers.0.batchnorm_attn.running_var", "encoder.layers.0.batchnorm_attn.num_batches_tracked", "encoder.layers.0.ff.0.weight", "encoder.layers.0.ff.0.bias", "encoder.layers.0.ff.2.weight", "encoder.layers.0.ff.2.bias", "encoder.layers.0.batchnorm_ffn.weight", "encoder.layers.0.batchnorm_ffn.bias", "encoder.layers.0.batchnorm_ffn.running_mean", "encoder.layers.0.batchnorm_ffn.running_var", "encoder.layers.0.batchnorm_ffn.num_batches_tracked", "encoder.layers.1.self_attn.W_Q.weight", "encoder.layers.1.self_attn.W_K.weight", "encoder.layers.1.self_attn.W_V.weight", "encoder.layers.1.self_attn.W_O.weight", "encoder.layers.1.batchnorm_attn.weight", "encoder.layers.1.batchnorm_attn.bias", "encoder.layers.1.batchnorm_attn.running_mean", "encoder.layers.1.batchnorm_attn.running_var", "encoder.layers.1.batchnorm_attn.num_batches_tracked", "encoder.layers.1.ff.0.weight", "encoder.layers.1.ff.0.bias", "encoder.layers.1.ff.2.weight", "encoder.layers.1.ff.2.bias", "encoder.layers.1.batchnorm_ffn.weight", "encoder.layers.1.batchnorm_ffn.bias", "encoder.layers.1.batchnorm_ffn.running_mean", "encoder.layers.1.batchnorm_ffn.running_var", "encoder.layers.1.batchnorm_ffn.num_batches_tracked", "encoder.layers.2.self_attn.W_Q.weight", "encoder.layers.2.self_attn.W_K.weight", "encoder.layers.2.self_attn.W_V.weight", "encoder.layers.2.self_attn.W_O.weight", "encoder.layers.2.batchnorm_attn.weight", "encoder.layers.2.batchnorm_attn.bias", "encoder.layers.2.batchnorm_attn.running_mean", "encoder.layers.2.batchnorm_attn.running_var", "encoder.layers.2.batchnorm_attn.num_batches_tracked", "encoder.layers.2.ff.0.weight", "encoder.layers.2.ff.0.bias", "encoder.layers.2.ff.2.weight", "encoder.layers.2.ff.2.bias", "encoder.layers.2.batchnorm_ffn.weight", "encoder.layers.2.batchnorm_ffn.bias", "encoder.layers.2.batchnorm_ffn.running_mean", "encoder.layers.2.batchnorm_ffn.running_var", "encoder.layers.2.batchnorm_ffn.num_batches_tracked", "head.1.weight", "head.1.bias". 
```

do you have any idea why it works initially and fails at a certain point? This state dict lookls like an internal function of TSAI

**Comment by oguiza** [comment]
Hi @geoHeil,
Based on the trace back, it seems you are trying to load the weights from a transformer model into an InceptionTimePlus architecture. Please, review the origin of the weights you are trying to load.
