### ISSUE TITLE
TypeError: no implementation found for 'torch.Tensor.masked_fill_' on types that implement __torch_function__: [00000227BADAEF90, 00000227BADAE930]

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#295]
I previously (with version 2.22, did not have an issue when making predictions. However, now, when trying to save a model, and then load the model to get predictions, I get the aforementioned error:

```

 |--------------------| 0.00% [0/1 00:00<00:00]Traceback (most recent call last):

  File "C:\Users\sergio\AppData\Local\Temp/ipykernel_20352/2006872649.py", line 1, in <module>
    probas, _, preds = learn.get_X_preds(X)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\inference.py", line 21, in get_X_preds
    output = list(self.get_preds(dl=dl, with_input=with_input, with_decoded=with_decoded, with_loss=with_loss, **kwargs))

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\learner.py", line 253, in get_preds
    self._do_epoch_validate(dl=dl)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\learner.py", line 203, in _do_epoch_validate
    with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\learner.py", line 169, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\learner.py", line 36, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\learner.py", line 172, in _do_one_batch
    self.pred = self.model(*self.xb)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\models\TSTPlus.py", line 211, in forward
    z = self.encoder(u, key_padding_mask=key_padding_mask, attn_mask=self.attn_mask)    # z: [bs x q_len x d_model]

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\models\TSTPlus.py", line 139, in forward
    for mod in self.layers: output, scores = mod(output, prev=scores, key_padding_mask=key_padding_mask, attn_mask=attn_mask)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\models\TSTPlus.py", line 100, in forward
    src2, attn, scores = self.self_attn(src, src, src, prev, key_padding_mask=key_padding_mask, attn_mask=attn_mask)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\models\layers.py", line 1062, in forward
    output, attn_weights, attn_scores = self.sdp_attn(q_s, k_s, v_s, prev=prev, key_padding_mask=key_padding_mask, attn_mask=attn_mask)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\models\layers.py", line 1008, in forward
    attn_scores.masked_fill_(key_padding_mask.unsqueeze(1).unsqueeze(2), -np.inf)

TypeError: no implementation found for 'torch.Tensor.masked_fill_' on types that implement __torch_function__: [00000227BADAEF90, 00000227BADAE930]
```
I am using CUDA and the following specs:

```
pytorch                   1.10.0          py3.9_cuda11.3_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch                     1.9.1                    pypi_0    pypi
torchaudio                0.10.0               py39_cu113    pytorch
torchvision               0.11.1               py39_cu113    pytorch
fastai                    2.5.3                    pypi_0    pypi
tsai                      0.2.23                   pypi_0    pypi
cudatoolkit               11.3.1               h59b6b97_2
```
Code being used:
`learn.save_all(save_path)`
[...]
```
learn = load_all(model_path)     
X, y = SlidingWindow(look_back, get_x = list(df.columns), get_y=[], horizon=horizon)(df)
probas, _, preds = learn.get_X_preds(X)
```

**Comment by oguiza** [comment]
Hi @strakehyr , 
I'd never seen this type of issue before. But it seems related to a Pytorch version. 

Could you please try using this and see if the issue persists? 
```bash
learn.export(model_path) # when you finish training
```
and then
```bash
from tsai.inference import load_learner
learn = load_learner(model_path)     
X, y = SlidingWindow(look_back, get_x = list(df.columns), get_y=[], horizon=horizon)(df)
probas, _, preds = learn.get_X_preds(X)
```

**Comment by oguiza** [comment]
Hi @strakehyr,
Could you please share with me and the rest of what was the issue and how did you fix it? I was investigating it when you closed it.

**Comment by strakehyr** [comment]
Hi Oguiza,
so when I had a closer look, a very small part of the df had nan values. Anyway, ow that I have fixed the issue, I am getting the following:
```
probas, _, preds = learn.get_X_preds(X)
                                                 Traceback (most recent call last):

  File "C:\Users\sergio\AppData\Local\Temp/ipykernel_20352/2006872649.py", line 1, in <module>
    probas, _, preds = learn.get_X_preds(X)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\inference.py", line 23, in get_X_preds
    output[2 + with_input] = self.dls.tls[-1].tfms.decode(output[2 + with_input])

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\transform.py", line 208, in decode
    if full: return compose_tfms(o, tfms=self.fs, is_enc=False, reverse=True, split_idx=self.split_idx)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\transform.py", line 150, in compose_tfms
    x = f(x, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\transform.py", line 74, in decode
    def decode  (self, x, **kwargs): return self._call('decodes', x, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\transform.py", line 83, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\transform.py", line 89, in _do_call
    return retain_type(f(x, **kwargs), x, ret)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\dispatch.py", line 118, in __call__
    return f(*args, **kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\data\core.py", line 108, in decodes
    def decodes(self, o): return TitledFloat(o) if o.ndim==0 else TitledTuple(o_.item() for o_ in o)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastcore\basics.py", line 632, in __new__
    try: x = tuple(iter(x))

  File "C:\Users\sergio\Anaconda3\lib\site-packages\tsai\data\core.py", line 108, in <genexpr>
    def decodes(self, o): return TitledFloat(o) if o.ndim==0 else TitledTuple(o_.item() for o_ in o)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\fastai\torch_core.py", line 340, in __torch_function__
    res = super().__torch_function__(func, types, args=args, kwargs=kwargs)

  File "C:\Users\sergio\Anaconda3\lib\site-packages\torch\_tensor.py", line 1051, in __torch_function__
    ret = func(*args, **kwargs)

ValueError: only one element tensors can be converted to Python scalars
```
any clues for this one?

**Comment by strakehyr** [comment]
> 

I am getting this error for regular predictions (no saving/loading required).

**Comment by oguiza** [comment]
Please, if you have a new issue create a separate one. Don't create an issue chain. I just reopened it because you created an issue that I investigated but you suddenly close without explaining why. 
I'll close the issue now. Please, reopen is this initial error reappers.
