### ISSUE TITLE
Beginner--An error is reported at runtime

### ISSUE THREAD

**Issue by julyao-yph** [timeseriesAI/tsai#413]
As a beginner，I feel very troubled，can you help me？

**I ran the first sample code you gave**
from tsai.all import *
X, y, splits = get_classification_data('ECG200', split_data=False)
batch_tfms = TSStandardize()
clf = TSClassifier(X, y, splits=splits, arch=InceptionTimePlus, batch_tfms=batch_tfms, metrics=accuracy, cbs=ShowGraph())
clf.fit_one_cycle(100, 3e-4)
clf.export("models/clf.pkl") # make sure you set the path to a folder that already exists

**But an error is reported at runtime**
W:\miniconda3\envs\mytsai\python.exe W:/PycharmProjects/pythonProjecttsai/main.py
epoch     train_loss  valid_loss  accuracy  time    
0         0.651254    0.686690    0.640000  00:01     
Figure(600x400)
Traceback (most recent call last):
  File "W:/PycharmProjects/pythonProjecttsai/main.py", line 5, in <module>
    clf.fit_one_cycle(100, 3e-4)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\callback\schedule.py", line 116, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\learner.py", line 212, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\learner.py", line 165, in _with_events
    self(f'after_{event_type}');  final()
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastcore\foundation.py", line 155, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastcore\basics.py", line 698, in map_ex
    return list(res)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastcore\basics.py", line 683, in __call__
    return self.func(*fargs, **kwargs)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\fastai\callback\core.py", line 45, in __call__
    if self.run and _run: res = getattr(self, event_name, noop)()
  File "W:\miniconda3\envs\mytsai\lib\site-packages\tsai\callback\core.py", line 111, in after_epoch
    self.update_graph([(iters, rec.losses), (self.nb_batches, val_losses)], x_bounds, y_bounds)
  File "W:\miniconda3\envs\mytsai\lib\site-packages\tsai\callback\core.py", line 130, in update_graph
    self.graph_out.update(self.graph_ax.figure)
AttributeError: 'NoneType' object has no attribute 'update'

Process finished with exit code 1

**Comment by oguiza** [comment]
Could you please run this code and post the output: 

```bash
from tsai.all import *
my_setup()
```
I've just tested your code and worked well. This is the setup where I've tested it:

os             : Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
python         : 3.7.12
tsai           : 0.2.26
fastai         : 2.5.3
fastcore       : 1.3.29
torch          : 1.10.0+cu111
n_cpus         : 2
device         : cuda (Tesla T4)

**Comment by etibuteau** [comment]
Hi, I had the same problem when running locally on my machine, it comes from **cbs=ShowGraph()** in **clf = TSClassifier(X, y, splits=splits, arch=InceptionTimePlus, batch_tfms=batch_tfms, metrics=accuracy, cbs=ShowGraph())**. 

You can just remove it and your code should work.

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response. Please, reopen if necessary.
