### ISSUE TITLE
Cannot use XCM on multivariate regression dataset

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#429]
Hi all,
I tried using XCM with a multivariate regression dataset and I got the following error. Since I am unfamiliar with this approach I reckon it might be misuse. 

```
model.show_gradcam(xb[0], yb[0])
Traceback (most recent call last):

  File "C:\Users\user\AppData\Local\Temp/ipykernel_20360/1671984503.py", line 1, in <module>
    model.show_gradcam(xb[0], yb[0])

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\XCM.py", line 65, in show_gradcam
    att_maps = get_attribution_map(self, [self.conv2dblock, self.conv1dblock], x, y=y, detach=detach, cpu=cpu, apply_relu=apply_relu)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\explainability.py", line 42, in get_attribution_map
    A_k, w_ck = get_acts_and_grads(model, modules, x, y, detach=detach, cpu=cpu)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\explainability.py", line 21, in get_acts_and_grads
    preds = model.eval()(x)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\XCM.py", line 41, in forward
    x1 = self.conv2dblock(x)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\layers.py", line 111, in forward
    return self.conv2d_same(self.pad(self.padding)(x))

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

  File "C:\Users\user\Anaconda3\lib\site-packages\fastai\torch_core.py", line 340, in __torch_function__
    res = super().__torch_function__(func, types, args=args, kwargs=kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\_tensor.py", line 1051, in __torch_function__
    ret = func(*args, **kwargs)

```
`RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

The code I used was:

```
X, y = SlidingWindow(look_back, get_x = list(df.iloc[:,n_outputs:].columns), get_y = (df.iloc[:,0].name), horizon=horizon)(df)
y = y.reshape(y.shape[0], 1, y.shape[1])
splits = get_splits(y, n_splits=1, valid_size=1-train_ratio, shuffle=False)
check_data(X, y, splits)
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms)
model =  XCM(dls.vars, dls.c, dls.len)
learn = ts_learner(dls, model, metrics=accuracy)
xb, yb = dls.one_batch()
model.show_gradcam(xb[0], yb[0])
```

**Comment by oguiza** [comment]
Hi @strakehyr ,
Based on this: 
```
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```
the issue is that the model weights are in the CPU while the input type (xb coming from the dataloader) are in the GPU (cuda). They need to be o the same device. 
You can try: 
```
model.to(device).show_gradcam(xb[0], yb[0])
```
model.to(device) will move the model parameters to the GPU.

**Comment by strakehyr** [comment]
Thank you @oguiza! Mind my lack of expertise, but now I am getting the following:
```
  File "C:\Users\user\AppData\Local\Temp/ipykernel_1396/1675477409.py", line 1, in <module>
    model.to(device).show_gradcam(xb[0], yb[0])

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\XCM.py", line 65, in show_gradcam
    att_maps = get_attribution_map(self, [self.conv2dblock, self.conv1dblock], x, y=y, detach=detach, cpu=cpu, apply_relu=apply_relu)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\explainability.py", line 42, in get_attribution_map
    A_k, w_ck = get_acts_and_grads(model, modules, x, y, detach=detach, cpu=cpu)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\models\explainability.py", line 24, in get_acts_and_grads
    if preds.shape[0] == 1: preds[0, y].backward()

  File "C:\Users\user\Anaconda3\lib\site-packages\fastai\torch_core.py", line 340, in __torch_function__
    res = super().__torch_function__(func, types, args=args, kwargs=kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\_tensor.py", line 1051, in __torch_function__
    ret = func(*args, **kwargs)
```

`IndexError: tensors used as indices must be long, byte or bool tensors`

**Comment by oguiza** [comment]
Hi @strakehyr,
I've checked this code works as expected: 
```python
from tsai.data.basics import *
from tsai.learner import *

dsid = 'NATOPS'
X, y, splits = get_UCR_data(dsid, split_data=False)
tfms = [None, TSCategorize()]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
model =  XCMPlus(dls.vars, dls.c, dls.len)
learn = ts_learner(dls, model, metrics=accuracy)
xb, yb = dls.one_batch()
learn.model.to(xb.device).show_gradcam(xb[0], yb[0])
```
However, you are passing a y with 3 dimensions. And gradients can be implicitly created only for scalar outputs. So this is not expected to work.
For example this code will fail: 
```python
from tsai.data.basics import *
from tsai.learner import *

dsid = 'NATOPS'
X, y, splits = get_UCR_data(dsid, split_data=False)
y = y.reshape(-1, 1,1).repeat(2, 1)
tfms = [None, TSCategorize()]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
model =  XCMPlus(dls.vars, dls.c, dls.len)
learn = ts_learner(dls, model, metrics=accuracy)
xb, yb = dls.one_batch()
learn.model.to(xb.device).show_gradcam(xb[0], yb[0])
```

**Comment by strakehyr** [comment]
Thank you again.
