### ISSUE TITLE
Import package kills kernel

### ISSUE THREAD

**Issue by oustella** [timeseriesAI/tsai#456]
Hi - I installed the tsai package via Poetry. When invoking `from tsai.all import *`, the Jupyter kernel dies. At first the error says "Disposing session as kernel process died ExitCode: undefined, Reason: /Users/oustella/Library/Caches/pypoetry/virtualenvs/hbf-E6tUn0h8-py3.8/lib/python3.8/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/oustella/Library/Caches/pypoetry/virtualenvs/hbf-E6tUn0h8-py3.8/lib/python3.8/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'be1a2d34-60b6-44b2-a0d6-3a68ca8b9e44' instead of 'b"be1a2d34-60b6-44b2-a0d6-3a68ca8b9e44"'.
  warn("

After I down-versioned traitlets to 4.3.3 based on this [StackOverflow discussion](https://stackoverflow.com/questions/67036168/kernel-died-with-exit-code-1vs-code), it still crashes but now with an undefined error code. I'd appreciate any pointers!

Error 13:02:48: Disposing session as kernel process died ExitCode: undefined, Reason: 
Info 13:02:48: Dispose Kernel process
Error 13:02:48: Raw kernel process exited code: undefined
Warn 13:02:48: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1204175)
	at /Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223227
	at Map.forEach (<anonymous>)
	at v._clearKernelState (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223212)
	at v.dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1216694)
	at /Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533674
	at t.swallowExceptions (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:913059)
	at dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533652)
	at t.RawSession.dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:537330)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
Warn 13:02:48: Cell completed with errors [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1204175)
	at /Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223227
	at Map.forEach (<anonymous>)
	at v._clearKernelState (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1223212)
	at v.dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1216694)
	at /Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533674
	at t.swallowExceptions (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:913059)
	at dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:533652)
	at t.RawSession.dispose (/Users/oustella/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:537330)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]

**Comment by oguiza** [comment]
Hi @oustella, I'm sorry but I'm not familiar with Poetry. 
There are 2 recommended installation processes described [here](https://github.com/timeseriesAI/tsai#installation).
Sorry I can't be of more help. I hope others can.

**Comment by ryendu** [comment]
I'm experiencing the same issue of `from tsai.all import *` killing the kernel. I installed with pip on an m1 mac which might be the issue.

**Comment by oguiza** [comment]
> I'm experiencing the same issue of from tsai.all import * killing the kernel. I installed with pip on an m1 mac which might be the issue.

The Pytorch team is working on the M1 mac support. This is the latest update I heard from them: https://github.com/pytorch/pytorch/issues/47702#issuecomment-965625139

I'm afraid we'll have to wait.

**Comment by oustella** [comment]
@oguiza  no worries. Thanks for looking into this and for creating this wonderful library. I can use Google Colab for now while experimenting how to install it to my local virtualenvs.

**Comment by oguiza** [comment]
@oustella, are you ok if I close this issue then? If you find there's anything to do from my side you can create a new issue.
