### ISSUE TITLE
TypeError: no implementation found for 'torch.stack' on types that implement __torch_function__: [00000258B1703450, 00000258B17034B0]

### ISSUE THREAD

**Issue by sxk000** [timeseriesAI/tsai#570]
pip install tsai

Successfully installed attrs-22.1.0 blis-0.7.8 catalogue-2.0.8 certifi-2022.6.15 charset-normalizer-2.1.1 click-8.1.3 cymem-2.0.6 fastai-2.7.9 fastcore-1.5.22 fastdownload-0.0.7 fastjsonschema-2.16.1 fastprogress-1.0.3 idna-3.3 imbalanced-learn-0.9.0 importlib-resources-5.9.0 jinja2-3.1.2 jsonschema-4.14.0 langcodes-3.3.0 llvmlite-0.39.0 murmurhash-1.0.8 nbformat-5.4.0 numba-0.56.0 pathy-0.6.2 pkgutil-resolve-name-1.3.10 preshed-3.0.7 pydantic-1.9.2 pyrsistent-0.18.1 pyts-0.12.0 requests-2.28.1 smart-open-5.2.1 spacy-3.4.1 spacy-legacy-3.0.10 spacy-loggers-1.0.3 srsly-2.4.4 thinc-8.1.0 torch-1.11.0 torchvision-0.12.0 tqdm-4.64.0 tsai-0.3.1 typer-0.4.2 typing-extensions-4.1.1 urllib3-1.26.12 wasabi-0.10.1

run tutorial/03_Time_Series_Transforms.ipynb
but got error:
Traceback (most recent call last):
  File "tsai-main\03_Time_Series_Transforms.py", line 58, in <module>
    dls.show_batch(unique=True, sharex=True, sharey=True)
  File "tsai-main\tsai\data\core.py", line 634, in show_batch
    b = self.unique_batch(max_n=max_n)
  File "tsai-main\tsai\data\core.py", line 617, in unique_batch
    b = (types[0](stack(x)), types[1](stack(y))) if out_len == 2 else (types[0](stack(x)), )
  File "tsai-main\tsai\utils.py", line 340, in stack
    return retain_type(torch.stack(tuple(o), dim=axis),  o[0]) if retain else torch.stack(tuple(o), dim=axis)
TypeError: no implementation found for 'torch.stack' on types that implement __torch_function__: [00000258B1703450, 00000258B17034B0]

what is wrong? what i can do?

**Comment by oguiza** [comment]
Issue closed due to lack of response.

**Comment by lmlzk** [comment]
lib\site-packages\tsai\utils.py in stack(o, axis, retain)
    413     if hasattr(o, '__array__'): return o
    414     if isinstance(o[0], torch.Tensor):
--> 415         return retain_type(torch.stack(tuple(o), dim=axis),  o[0]) if retain else torch.stack(tuple(o), dim=axis)
    416     else:
    417         return retain_type(np.stack(o, axis), o[0]) if retain else np.stack(o, axis)

TypeError: no implementation found for 'torch.stack' on types that implement __torch_function__: [<class 'tsai.data.core.TSTensor'>, <class 'fastai.torch_core.TensorCategory'>]


Pytorch to 1.13.0

**Comment by oguiza** [comment]
Hi @lmlzk ,
If you have a similar issue, please create a new issue. Don't reuse a closed issue as it won't be noticed.
