### ISSUE TITLE
Is it because the new version of torch does not have the attribute "asarray"？

### ISSUE THREAD

**Issue by ITP0** [timeseriesAI/tsai#816]
**When I use the "TSForecast" method, an error occurs**

Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    TSForecaster(X, y, splits=splits, arch='PatchTST', arch_config=arch_config, metrics=mse)
  File "C:\Users\86152\AppData\Local\Programs\Python\Python39\lib\site-packages\tsai-0.3.8-py3.9.egg\tsai\tslearner.py", line 206, in __init__
    dls = get_ts_dls(X, y=y, splits=splits, sel_vars=sel_vars, sel_steps=sel_steps, tfms=tfms, inplace=inplace,
  File "C:\Users\86152\AppData\Local\Programs\Python\Python39\lib\site-packages\tsai-0.3.8-py3.9.egg\tsai\data\core.py", line 1095, in get_ts_dls
    dsets = TSDatasets(X, y, splits=splits, sel_vars=sel_vars, sel_steps=sel_steps, tfms=tfms, inplace=inplace)
  File "C:\Users\86152\AppData\Local\Programs\Python\Python39\lib\site-packages\tsai-0.3.8-py3.9.egg\tsai\data\core.py", line 491, in __init__
    tl.items = typ(tl.items)
  File "C:\Users\86152\AppData\Local\Programs\Python\Python39\lib\site-packages\tsai-0.3.8-py3.9.egg\tsai\data\core.py", line 75, in __new__
    o = torch.asarray(o, dtype=dtype, device=device, copy=copy, requires_grad=requires_grad)
AttributeError: module 'torch' has no attribute 'asarray'

**Comment by oguiza** [comment]
Hi @ITP0,
I'm not sure what tsai version and torch version you are using. 
But the new version of torch >=2.0 has asarray: https://pytorch.org/docs/stable/generated/torch.asarray.html
