### ISSUE TITLE
Mask Shape Mismatch on IEEEPPG Dataset Using TSTPlus

### ISSUE THREAD

**Issue by xanderdunn** [timeseriesAI/tsai#86]
Attempting to train 100% unsupervised `IEEEPPG` dataset using [TSBERT](https://github.com/timeseriesAI/tsai/blob/master/tutorial_nbs/08_Self_Supervised_TSBERT.ipynb) with `TSTPlus` model (instead of `InceptionTimePlus`) produces this error:
```
Getting data...
Dataset: IEEEPPG
X      : (3096, 5, 1000)
y      : (3096,)
splits : (#1768) [0,1,2,3,4,5,6,7,8,9...] (#1328) [1768,1769,1770,1771,1772,1773,1774,1775,1776,1777...]

X      - shape: [3096 samples x 5 features x 1000 timesteps]  type: memmap  dtype:float64  isnan: 0
y      - shape: (3096,)  type: memmap  dtype:float64  isnan: 0
splits - n_splits: 2 shape: [1768, 1328]  overlap: [False]
WandbCallback was not able to prepare a DataLoader for logging prediction samples -> tuple index out of range
epoch     train_loss  valid_loss  time
Traceback (most recent call last):
  File "./mydata/mydata/tsbert_baseline.py", line 137, in <module>
    run_benchmark_dataset()
  File "./mydata/mydata/tsbert_baseline.py", line 133, in run_benchmark_dataset
    train_self_supervised(X, y, splits, dataset_id, device, regression, architecture)
  File "./mydata/mydata/tsbert_baseline.py", line 52, in train_self_supervised
    learn.fit_one_cycle(200, 1e-4)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/callback/schedule.py", line 112, in fit_o$
e_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 211, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 202, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 196, in _do_epoch
    self._do_epoch_train()
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 188, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 166, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 184, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/learner.py", line 172, in _do_one_batch
    self.loss_grad = self.loss_func(self.pred, *self.yb)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_$
mpl
    result = self.forward(*input, **kwargs)
  File "/home/xander/dev/tsai/tsai/callback/MVP.py", line 105, in forward
    return self.crit(preds[self.mask], target[self.mask])
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/fastai/torch_core.py", line 329, in __torch_func$
ion__
    res = super().__torch_function__(func, types, args=args, kwargs=kwargs)
  File "/home/xander/anaconda3/envs/model/lib/python3.7/site-packages/torch/tensor.py", line 995, in __torch_function_$
    ret = func(*args, **kwargs)
IndexError: The shape of the mask [64, 5, 1000] at index 2 does not match the shape of the indexed tensor [64, 5, 512] at ind$
x 2
```

It appears to be specific to the `IEEEPG` dataset when using TSTPlus. IEEEPG + `InceptionTimePlus` trains fine. Other regression datasets such as `AppliancesEnergy` and `LiveFuelMoistureContent` train just fine with TSTPlus. Classification tasks like `FaceDetection` and `InsectWingBeat` also work fine with the `TSTPlus` model. 

I'm on master commit 2d334d1bc605287f1b6033007f4014d62dd49566. This reproduces on both Python 3.6 and 3.7. Reverting tsai code back to February 10th had no effect on this.

**Comment by xanderdunn** [comment]
This appears to happen on any dataset where the sample length (aka window size) is larger than 512. This occurred on my own dataset when I chose a window_size of 513-1024. `IEEEPG` has a sample length of 1000, so it causes the same problem. All of the regression datasets that work have a sample length < 512: `AppliancesEnergy` is 144 sample length, and `LiveFuelMoistureContent` has 365 sample length. 

Is there something that limits the size of the mask to 512 when using the `TSTPlus` model?

**Comment by oguiza** [comment]
Attention models demand a lot of memory. That's why I included a max_seq_len hyperparameter to avoid using TSTPlus with very long sequences .This prevents getting OOM errors. 
Having said that, if you want to use TSTPlus with TSBert, you will need to set that hyperparameter to None. But if the time series is long, you will need a large RAM.

**Comment by xanderdunn** [comment]
Thanks, setting `TSTPlus(max_seq_length=None)` solved this issue. Out of memory errors are definitely the expected behavior here. Sufficiently large batch size will produce out of memory errors on most models. For example, training TSBERT with TSTPlus backend on the IEEEPPG dataset (1000 sample length) works with batch size 32 on my A100.
